# Generated by Django 3.1.5 on 2021-02-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='', verbose_name='file path')),
                ('pub_datetime', models.DateTimeField(verbose_name='date published')),
                ('doc_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_datetime', models.DateTimeField(verbose_name='date published')),
                ('doc_file', models.FileField(upload_to='', verbose_name='file path')),
                ('doc_name', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='news text')),
            ],
        ),
    ]
