# Generated by Django 3.1.5 on 2021-02-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_file',
            field=models.FileField(upload_to='polls/static/', verbose_name='file path'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='doc_file',
            field=models.FileField(upload_to='polls/static/', verbose_name='file path'),
        ),
    ]
